name: StrikingEntrance
main: com.natoboram.spigot.strikingentrance.StrikingEntrance
version: 1.2.1
author: NatoBoram
description: Adds some lightning bolts for a striking Minecraft experience.
api:
    - "1.12"
    - "1.13"
    - "1.14"
    - "1.15"
api-version: "1.15"
